"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME = "Graphene"
APP = ['/Users/baddikushai/PycharmProjects/moduless/TASKS/Work_with_MAT/r_app/tr_main.py']
DATA_FILES = [('Images', ['форлог.png']),
              ('Images', ['форкос.jpg']),
              ('Images', ['форсин.jpg'])]
OPTIONS = {
    "packages": ["matplotlib", "numpy", "PIL"],
    "iconfile": "mathicon.icns",
    "argv_emulation": True,
    "plist": {
        'CFBundleName': APP_NAME,
        'CFBundleShortVersionString':'0.0.1',
        'CFBundleVersion': '0.0.1',
        'CFBundleIdentifier':'com.rh.TextTools',
        'NSHumanReadableCopyright': '@ My Name 2014'
    }
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
